import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

// const googleSans = localFont({ src: './googlesans.woff2',variable:'--font-google-sans' })
const googleSans = localFont({
  src: [

    {
      path: "../fonts/GoogleSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/GoogleSans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/GoogleSans-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/GoogleSans-Black.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-google-sans",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${googleSans.variable} font-sans`}>{children}</body>
    </html>
  );
}
